set $dblue #03002e
set $clay #2f343a
set $dark #000000
set $blue #203355 
set $white #ffffff
set $skyblue #2e9ef4 
set $grey20 #333333
set $grey60 #999999
set $desatblue #285577F
set $gray40 #666666 
set $navyblue #203355
set $red #900000
set $charcoal #484e50
set $deepcoal #292d2e

set $pink #FFC0CB

# target                 title  bg        text    indicator  border
client.focused		$dblue 	$desatblue $white  $skyblue  $desatblue
client.focused_inactive	$dblue 	$gray40   $white  $charcoal $gray40
client.unfocused	$dblue 	$grey20   $grey60 $deepcoal $grey20
client.urgent		$clay	$red      $white  $red      $red
client.placeholder	$dark	$dblue    $white  $dark     $dblue
client.background	$dblue	
