#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec ax; fi
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty2 ]]; then exec startx; fi
if [ "$DISPLAY" != "" ] && [ "$XAUTHORITY" = "" ]; then
    export XAUTHORITY=$HOME/.Xauthority
fi
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ms='mousepad'
alias pr='sudo pacman -R'
alias tear='rm -rf'

source ~/.bash_function
export PS1='[`pwd`]$ '
