[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
xrandr --output HDMI-0 --auto --right-of DP-2
xrandr --output DP-2 --auto --primary
xwallpaper --center ~/Pictures/Wallpapers/jinhsi.jpg
sxhkd &
dunst &
exec ~/.config/polybar/launch_polybar.sh &
exec i3
